### PR TITLE
Proposed sponsored talk policy for PyBay 2023

### PR DESCRIPTION
**Pull request by moshez**
Please vote on this via commenting "yes" or "no" on the pull request.

### CODE REVIEW

**Comment by jamesabel** [comment]
Yes

**Comment by polkapolka** [comment]
yes

**Comment by moshez** [comment]
Yes

**Comment by moshez** [comment]
Being that we have five people on the board, with three yes votes, the other votes cannot change the outcome. I will merge this, and note that this happened in the minutes of the next minute.

**Pull request merged**
